print("-              -")
print("- -          - -")
print("-   -       -  -")
print("-    - - - -   -")
print("-              -")
print("   ***     ***  ")
print("___          ___ ")
print(" -       -      -")
print("   -   -   -  -")